/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateEventRequest,
    CreateEventRequestFromJSON,
    CreateEventRequestToJSON,
} from '../models/CreateEventRequest';
import {
    type CreateMediaIntent201Response,
    CreateMediaIntent201ResponseFromJSON,
    CreateMediaIntent201ResponseToJSON,
} from '../models/CreateMediaIntent201Response';
import {
    type CreateMediaIntentRequest,
    CreateMediaIntentRequestFromJSON,
    CreateMediaIntentRequestToJSON,
} from '../models/CreateMediaIntentRequest';
import {
    type ErrorEnvelope,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
} from '../models/ErrorEnvelope';
import {
    type Event,
    EventFromJSON,
    EventToJSON,
} from '../models/Event';
import {
    type EventStatus,
    EventStatusFromJSON,
    EventStatusToJSON,
} from '../models/EventStatus';
import {
    type EventWithSession,
    EventWithSessionFromJSON,
    EventWithSessionToJSON,
} from '../models/EventWithSession';
import {
    type InternalJobResult,
    InternalJobResultFromJSON,
    InternalJobResultToJSON,
} from '../models/InternalJobResult';
import {
    type LinkIdentityRequest,
    LinkIdentityRequestFromJSON,
    LinkIdentityRequestToJSON,
} from '../models/LinkIdentityRequest';
import {
    type ListEvents200Response,
    ListEvents200ResponseFromJSON,
    ListEvents200ResponseToJSON,
} from '../models/ListEvents200Response';
import {
    type ListMedia200Response,
    ListMedia200ResponseFromJSON,
    ListMedia200ResponseToJSON,
} from '../models/ListMedia200Response';
import {
    type Media,
    MediaFromJSON,
    MediaToJSON,
} from '../models/Media';
import {
    type PublicEventMetadata,
    PublicEventMetadataFromJSON,
    PublicEventMetadataToJSON,
} from '../models/PublicEventMetadata';
import {
    type PublishEvent200Response,
    PublishEvent200ResponseFromJSON,
    PublishEvent200ResponseToJSON,
} from '../models/PublishEvent200Response';
import {
    type ScannerCallbackRequest,
    ScannerCallbackRequestFromJSON,
    ScannerCallbackRequestToJSON,
} from '../models/ScannerCallbackRequest';
import {
    type UpdateEventRequest,
    UpdateEventRequestFromJSON,
    UpdateEventRequestToJSON,
} from '../models/UpdateEventRequest';
import {
    type WambeProductEventV1,
    WambeProductEventV1FromJSON,
    WambeProductEventV1ToJSON,
} from '../models/WambeProductEventV1';

export interface AcceptScannerCallbackRequest {
    xWambeTimestamp: Date;
    xWambeNonce: string;
    scannerCallbackRequest: ScannerCallbackRequest;
}

export interface CompleteMediaUploadRequest {
    eventId: string;
    mediaId: string;
    idempotencyKey: string;
}

export interface CreateEventOperationRequest {
    idempotencyKey: string;
    createEventRequest: CreateEventRequest;
}

export interface CreateMediaIntentOperationRequest {
    eventId: string;
    idempotencyKey: string;
    createMediaIntentRequest: CreateMediaIntentRequest;
}

export interface DeleteEventRequest {
    idempotencyKey: string;
    eventId: string;
}

export interface DeleteMediaRequest {
    eventId: string;
    mediaId: string;
    idempotencyKey: string;
}

export interface GetEventRequest {
    eventId: string;
}

export interface GetPublicEventMetadataRequest {
    slug: string;
}

export interface LinkIdentityOperationRequest {
    idempotencyKey: string;
    linkIdentityRequest: LinkIdentityRequest;
}

export interface ListEventsRequest {
    status?: EventStatus;
    cursor?: string;
    limit?: number;
}

export interface ListMediaRequest {
    eventId: string;
}

export interface PublishEventRequest {
    eventId: string;
    idempotencyKey: string;
    ifMatch: string;
}

export interface RecordCreationMilestoneRequest {
    sessionId: string;
    idempotencyKey: string;
    wambeProductEventV1: WambeProductEventV1;
}

export interface UnpublishEventRequest {
    eventId: string;
    idempotencyKey: string;
    ifMatch: string;
}

export interface UpdateEventOperationRequest {
    idempotencyKey: string;
    ifMatch: string;
    eventId: string;
    updateEventRequest: UpdateEventRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for acceptScannerCallback without sending the request
     */
    async acceptScannerCallbackRequestOpts(requestParameters: AcceptScannerCallbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xWambeTimestamp'] == null) {
            throw new runtime.RequiredError(
                'xWambeTimestamp',
                'Required parameter "xWambeTimestamp" was null or undefined when calling acceptScannerCallback().'
            );
        }

        if (requestParameters['xWambeNonce'] == null) {
            throw new runtime.RequiredError(
                'xWambeNonce',
                'Required parameter "xWambeNonce" was null or undefined when calling acceptScannerCallback().'
            );
        }

        if (requestParameters['scannerCallbackRequest'] == null) {
            throw new runtime.RequiredError(
                'scannerCallbackRequest',
                'Required parameter "scannerCallbackRequest" was null or undefined when calling acceptScannerCallback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xWambeTimestamp'] != null) {
            headerParameters['X-Wambe-Timestamp'] = String(requestParameters['xWambeTimestamp']);
        }

        if (requestParameters['xWambeNonce'] != null) {
            headerParameters['X-Wambe-Nonce'] = String(requestParameters['xWambeNonce']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Wambe-Signature"] = await this.configuration.apiKey("X-Wambe-Signature"); // scannerHmac authentication
        }


        let urlPath = `/internal/scanner/callback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScannerCallbackRequestToJSON(requestParameters['scannerCallbackRequest']),
        };
    }

    /**
     * Accept one signed, single-use malware scan result
     */
    async acceptScannerCallbackRaw(requestParameters: AcceptScannerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.acceptScannerCallbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Accept one signed, single-use malware scan result
     */
    async acceptScannerCallback(requestParameters: AcceptScannerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.acceptScannerCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for completeMediaUpload without sending the request
     */
    async completeMediaUploadRequestOpts(requestParameters: CompleteMediaUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling completeMediaUpload().'
            );
        }

        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling completeMediaUpload().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling completeMediaUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}/media/{mediaId}/complete`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Verify quarantine upload and enqueue scanning
     */
    async completeMediaUploadRaw(requestParameters: CompleteMediaUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Media>> {
        const requestOptions = await this.completeMediaUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MediaFromJSON(jsonValue));
    }

    /**
     * Verify quarantine upload and enqueue scanning
     */
    async completeMediaUpload(requestParameters: CompleteMediaUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Media> {
        const response = await this.completeMediaUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createEvent without sending the request
     */
    async createEventRequestOpts(requestParameters: CreateEventOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createEvent().'
            );
        }

        if (requestParameters['createEventRequest'] == null) {
            throw new runtime.RequiredError(
                'createEventRequest',
                'Required parameter "createEventRequest" was null or undefined when calling createEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEventRequestToJSON(requestParameters['createEventRequest']),
        };
    }

    /**
     * Create an owned draft and creation session
     */
    async createEventRaw(requestParameters: CreateEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventWithSession>> {
        const requestOptions = await this.createEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventWithSessionFromJSON(jsonValue));
    }

    /**
     * Create an owned draft and creation session
     */
    async createEvent(requestParameters: CreateEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventWithSession> {
        const response = await this.createEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createMediaIntent without sending the request
     */
    async createMediaIntentRequestOpts(requestParameters: CreateMediaIntentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling createMediaIntent().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createMediaIntent().'
            );
        }

        if (requestParameters['createMediaIntentRequest'] == null) {
            throw new runtime.RequiredError(
                'createMediaIntentRequest',
                'Required parameter "createMediaIntentRequest" was null or undefined when calling createMediaIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}/media/intents`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMediaIntentRequestToJSON(requestParameters['createMediaIntentRequest']),
        };
    }

    /**
     * Create a private quarantine upload intent
     */
    async createMediaIntentRaw(requestParameters: CreateMediaIntentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateMediaIntent201Response>> {
        const requestOptions = await this.createMediaIntentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateMediaIntent201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a private quarantine upload intent
     */
    async createMediaIntent(requestParameters: CreateMediaIntentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateMediaIntent201Response> {
        const response = await this.createMediaIntentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEvent without sending the request
     */
    async deleteEventRequestOpts(requestParameters: DeleteEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteEvent().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling deleteEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Soft-delete an owned event and schedule media purge
     */
    async deleteEventRaw(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft-delete an owned event and schedule media purge
     */
    async deleteEvent(requestParameters: DeleteEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEventRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteMedia without sending the request
     */
    async deleteMediaRequestOpts(requestParameters: DeleteMediaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling deleteMedia().'
            );
        }

        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling deleteMedia().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling deleteMedia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}/media/{mediaId}`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Detach media and schedule active-storage purge
     */
    async deleteMediaRaw(requestParameters: DeleteMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteMediaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Detach media and schedule active-storage purge
     */
    async deleteMedia(requestParameters: DeleteMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMediaRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for dispatchDueScanJobs without sending the request
     */
    async dispatchDueScanJobsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("internalOidc", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/jobs/scan-dispatch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lease and dispatch due media scan jobs
     */
    async dispatchDueScanJobsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalJobResult>> {
        const requestOptions = await this.dispatchDueScanJobsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalJobResultFromJSON(jsonValue));
    }

    /**
     * Lease and dispatch due media scan jobs
     */
    async dispatchDueScanJobs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalJobResult> {
        const response = await this.dispatchDueScanJobsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEvent without sending the request
     */
    async getEventRequestOpts(requestParameters: GetEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one owned event management representation
     */
    async getEventRaw(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        const requestOptions = await this.getEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Get one owned event management representation
     */
    async getEvent(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.getEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPublicEventMetadata without sending the request
     */
    async getPublicEventMetadataRequestOpts(requestParameters: GetPublicEventMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling getPublicEventMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/public/events/{slug}/metadata`;
        urlPath = urlPath.replace('{slug}', encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return visibility-safe metadata for Next.js canonical and OG rendering
     */
    async getPublicEventMetadataRaw(requestParameters: GetPublicEventMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicEventMetadata>> {
        const requestOptions = await this.getPublicEventMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicEventMetadataFromJSON(jsonValue));
    }

    /**
     * Return visibility-safe metadata for Next.js canonical and OG rendering
     */
    async getPublicEventMetadata(requestParameters: GetPublicEventMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicEventMetadata> {
        const response = await this.getPublicEventMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for linkIdentity without sending the request
     */
    async linkIdentityRequestOpts(requestParameters: LinkIdentityOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling linkIdentity().'
            );
        }

        if (requestParameters['linkIdentityRequest'] == null) {
            throw new runtime.RequiredError(
                'linkIdentityRequest',
                'Required parameter "linkIdentityRequest" was null or undefined when calling linkIdentity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/link-identity`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LinkIdentityRequestToJSON(requestParameters['linkIdentityRequest']),
        };
    }

    /**
     * Link a verified provider identity after recent reauthentication
     */
    async linkIdentityRaw(requestParameters: LinkIdentityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.linkIdentityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Link a verified provider identity after recent reauthentication
     */
    async linkIdentity(requestParameters: LinkIdentityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.linkIdentityRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listEvents without sending the request
     */
    async listEventsRequestOpts(requestParameters: ListEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the authenticated host\'s events
     */
    async listEventsRaw(requestParameters: ListEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEvents200Response>> {
        const requestOptions = await this.listEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListEvents200ResponseFromJSON(jsonValue));
    }

    /**
     * List the authenticated host\'s events
     */
    async listEvents(requestParameters: ListEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEvents200Response> {
        const response = await this.listEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMedia without sending the request
     */
    async listMediaRequestOpts(requestParameters: ListMediaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling listMedia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}/media`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List upload, scan, and preview status
     */
    async listMediaRaw(requestParameters: ListMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMedia200Response>> {
        const requestOptions = await this.listMediaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListMedia200ResponseFromJSON(jsonValue));
    }

    /**
     * List upload, scan, and preview status
     */
    async listMedia(requestParameters: ListMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMedia200Response> {
        const response = await this.listMediaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publishEvent without sending the request
     */
    async publishEventRequestOpts(requestParameters: PublishEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling publishEvent().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling publishEvent().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling publishEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}/publish`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Validate and transactionally publish or republish an event
     */
    async publishEventRaw(requestParameters: PublishEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublishEvent200Response>> {
        const requestOptions = await this.publishEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublishEvent200ResponseFromJSON(jsonValue));
    }

    /**
     * Validate and transactionally publish or republish an event
     */
    async publishEvent(requestParameters: PublishEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublishEvent200Response> {
        const response = await this.publishEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recordCreationMilestone without sending the request
     */
    async recordCreationMilestoneRequestOpts(requestParameters: RecordCreationMilestoneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling recordCreationMilestone().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling recordCreationMilestone().'
            );
        }

        if (requestParameters['wambeProductEventV1'] == null) {
            throw new runtime.RequiredError(
                'wambeProductEventV1',
                'Required parameter "wambeProductEventV1" was null or undefined when calling recordCreationMilestone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/creation-sessions/{sessionId}/events`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WambeProductEventV1ToJSON(requestParameters['wambeProductEventV1']),
        };
    }

    /**
     * Record one allowlisted client milestone with server receipt time
     */
    async recordCreationMilestoneRaw(requestParameters: RecordCreationMilestoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.recordCreationMilestoneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Record one allowlisted client milestone with server receipt time
     */
    async recordCreationMilestone(requestParameters: RecordCreationMilestoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.recordCreationMilestoneRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for runRetentionJobs without sending the request
     */
    async runRetentionJobsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("internalOidc", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/jobs/retention`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Run due draft, media, idempotency, and nonce retention
     */
    async runRetentionJobsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalJobResult>> {
        const requestOptions = await this.runRetentionJobsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalJobResultFromJSON(jsonValue));
    }

    /**
     * Run due draft, media, idempotency, and nonce retention
     */
    async runRetentionJobs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalJobResult> {
        const response = await this.runRetentionJobsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unpublishEvent without sending the request
     */
    async unpublishEventRequestOpts(requestParameters: UnpublishEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling unpublishEvent().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling unpublishEvent().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling unpublishEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}/unpublish`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unpublish while preserving the stable slug
     */
    async unpublishEventRaw(requestParameters: UnpublishEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        const requestOptions = await this.unpublishEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Unpublish while preserving the stable slug
     */
    async unpublishEvent(requestParameters: UnpublishEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.unpublishEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEvent without sending the request
     */
    async updateEventRequestOpts(requestParameters: UpdateEventOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling updateEvent().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling updateEvent().'
            );
        }

        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling updateEvent().'
            );
        }

        if (requestParameters['updateEventRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEventRequest',
                'Required parameter "updateEventRequest" was null or undefined when calling updateEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{eventId}`;
        urlPath = urlPath.replace('{eventId}', encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEventRequestToJSON(requestParameters['updateEventRequest']),
        };
    }

    /**
     * Autosave partial event fields
     */
    async updateEventRaw(requestParameters: UpdateEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        const requestOptions = await this.updateEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Autosave partial event fields
     */
    async updateEvent(requestParameters: UpdateEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.updateEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
