/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEventRequest
 */
export interface CreateEventRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEventRequest
     */
    clientCreationKey: string;
    /**
     * 
     * @type {CreateEventRequestEligibilityEnum}
     * @memberof CreateEventRequest
     */
    eligibility: CreateEventRequestEligibilityEnum;
    /**
     * 
     * @type {CreateEventRequestDeviceClassEnum}
     * @memberof CreateEventRequest
     */
    deviceClass?: CreateEventRequestDeviceClassEnum;
    /**
     * 
     * @type {CreateEventRequestNetworkQualityEnum}
     * @memberof CreateEventRequest
     */
    networkQuality?: CreateEventRequestNetworkQualityEnum;
}


/**
 * @export
 */
export const CreateEventRequestEligibilityEnum = {
    EligibleFirstTime: 'eligible_first_time',
    ResumedDraft: 'resumed_draft',
    StaffAssisted: 'staff_assisted'
} as const;
export type CreateEventRequestEligibilityEnum = typeof CreateEventRequestEligibilityEnum[keyof typeof CreateEventRequestEligibilityEnum];

/**
 * @export
 */
export const CreateEventRequestDeviceClassEnum = {
    Mobile: 'mobile',
    Tablet: 'tablet',
    Desktop: 'desktop',
    Unknown: 'unknown'
} as const;
export type CreateEventRequestDeviceClassEnum = typeof CreateEventRequestDeviceClassEnum[keyof typeof CreateEventRequestDeviceClassEnum];

/**
 * @export
 */
export const CreateEventRequestNetworkQualityEnum = {
    Good: 'good',
    Fair: 'fair',
    Poor: 'poor',
    Unknown: 'unknown'
} as const;
export type CreateEventRequestNetworkQualityEnum = typeof CreateEventRequestNetworkQualityEnum[keyof typeof CreateEventRequestNetworkQualityEnum];


/**
 * Check if a given object implements the CreateEventRequest interface.
 */
export function instanceOfCreateEventRequest(value: object): value is CreateEventRequest {
    if (!('clientCreationKey' in value) || value['clientCreationKey'] === undefined) return false;
    if (!('eligibility' in value) || value['eligibility'] === undefined) return false;
    return true;
}

export function CreateEventRequestFromJSON(json: any): CreateEventRequest {
    return CreateEventRequestFromJSONTyped(json, false);
}

export function CreateEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientCreationKey': json['clientCreationKey'],
        'eligibility': json['eligibility'],
        'deviceClass': json['deviceClass'] == null ? undefined : json['deviceClass'],
        'networkQuality': json['networkQuality'] == null ? undefined : json['networkQuality'],
    };
}

export function CreateEventRequestToJSON(json: any): CreateEventRequest {
    return CreateEventRequestToJSONTyped(json, false);
}

export function CreateEventRequestToJSONTyped(value?: CreateEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clientCreationKey': value['clientCreationKey'],
        'eligibility': value['eligibility'],
        'deviceClass': value['deviceClass'],
        'networkQuality': value['networkQuality'],
    };
}

