/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';

/**
 * 
 * @export
 * @interface CreateMediaIntent201Response
 */
export interface CreateMediaIntent201Response {
    /**
     * 
     * @type {Media}
     * @memberof CreateMediaIntent201Response
     */
    media: Media;
    /**
     * 
     * @type {string}
     * @memberof CreateMediaIntent201Response
     */
    uploadUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateMediaIntent201Response
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the CreateMediaIntent201Response interface.
 */
export function instanceOfCreateMediaIntent201Response(value: object): value is CreateMediaIntent201Response {
    if (!('media' in value) || value['media'] === undefined) return false;
    if (!('uploadUrl' in value) || value['uploadUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function CreateMediaIntent201ResponseFromJSON(json: any): CreateMediaIntent201Response {
    return CreateMediaIntent201ResponseFromJSONTyped(json, false);
}

export function CreateMediaIntent201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMediaIntent201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'media': MediaFromJSON(json['media']),
        'uploadUrl': json['uploadUrl'],
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function CreateMediaIntent201ResponseToJSON(json: any): CreateMediaIntent201Response {
    return CreateMediaIntent201ResponseToJSONTyped(json, false);
}

export function CreateMediaIntent201ResponseToJSONTyped(value?: CreateMediaIntent201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media': MediaToJSON(value['media']),
        'uploadUrl': value['uploadUrl'],
        'expiresAt': value['expiresAt'].toISOString(),
    };
}

