/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaRole } from './MediaRole';
import {
    MediaRoleFromJSON,
    MediaRoleFromJSONTyped,
    MediaRoleToJSON,
    MediaRoleToJSONTyped,
} from './MediaRole';

/**
 * 
 * @export
 * @interface CreateMediaIntentRequest
 */
export interface CreateMediaIntentRequest {
    /**
     * 
     * @type {MediaRole}
     * @memberof CreateMediaIntentRequest
     */
    role: MediaRole;
    /**
     * 
     * @type {string}
     * @memberof CreateMediaIntentRequest
     */
    filename: string;
    /**
     * 
     * @type {CreateMediaIntentRequestClaimedMimeTypeEnum}
     * @memberof CreateMediaIntentRequest
     */
    claimedMimeType: CreateMediaIntentRequestClaimedMimeTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateMediaIntentRequest
     */
    sizeBytes: number;
}


/**
 * @export
 */
export const CreateMediaIntentRequestClaimedMimeTypeEnum = {
    ImageJpeg: 'image/jpeg',
    ImagePng: 'image/png',
    ImageWebp: 'image/webp',
    ApplicationPdf: 'application/pdf'
} as const;
export type CreateMediaIntentRequestClaimedMimeTypeEnum = typeof CreateMediaIntentRequestClaimedMimeTypeEnum[keyof typeof CreateMediaIntentRequestClaimedMimeTypeEnum];


/**
 * Check if a given object implements the CreateMediaIntentRequest interface.
 */
export function instanceOfCreateMediaIntentRequest(value: object): value is CreateMediaIntentRequest {
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('claimedMimeType' in value) || value['claimedMimeType'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    return true;
}

export function CreateMediaIntentRequestFromJSON(json: any): CreateMediaIntentRequest {
    return CreateMediaIntentRequestFromJSONTyped(json, false);
}

export function CreateMediaIntentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMediaIntentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'role': MediaRoleFromJSON(json['role']),
        'filename': json['filename'],
        'claimedMimeType': json['claimedMimeType'],
        'sizeBytes': json['sizeBytes'],
    };
}

export function CreateMediaIntentRequestToJSON(json: any): CreateMediaIntentRequest {
    return CreateMediaIntentRequestToJSONTyped(json, false);
}

export function CreateMediaIntentRequestToJSONTyped(value?: CreateMediaIntentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': MediaRoleToJSON(value['role']),
        'filename': value['filename'],
        'claimedMimeType': value['claimedMimeType'],
        'sizeBytes': value['sizeBytes'],
    };
}

