/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorEnvelopeError
 */
export interface ErrorEnvelopeError {
    /**
     * 
     * @type {string}
     * @memberof ErrorEnvelopeError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorEnvelopeError
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorEnvelopeError
     */
    requestId: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ErrorEnvelopeError
     */
    fieldErrors?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the ErrorEnvelopeError interface.
 */
export function instanceOfErrorEnvelopeError(value: object): value is ErrorEnvelopeError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function ErrorEnvelopeErrorFromJSON(json: any): ErrorEnvelopeError {
    return ErrorEnvelopeErrorFromJSONTyped(json, false);
}

export function ErrorEnvelopeErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorEnvelopeError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'requestId': json['requestId'],
        'fieldErrors': json['fieldErrors'] == null ? undefined : json['fieldErrors'],
    };
}

export function ErrorEnvelopeErrorToJSON(json: any): ErrorEnvelopeError {
    return ErrorEnvelopeErrorToJSONTyped(json, false);
}

export function ErrorEnvelopeErrorToJSONTyped(value?: ErrorEnvelopeError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'requestId': value['requestId'],
        'fieldErrors': value['fieldErrors'],
    };
}

