/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorEnvelopeError } from './ErrorEnvelopeError';
import {
    ErrorEnvelopeErrorFromJSON,
    ErrorEnvelopeErrorFromJSONTyped,
    ErrorEnvelopeErrorToJSON,
    ErrorEnvelopeErrorToJSONTyped,
} from './ErrorEnvelopeError';

/**
 * 
 * @export
 * @interface ErrorEnvelope
 */
export interface ErrorEnvelope {
    /**
     * 
     * @type {ErrorEnvelopeError}
     * @memberof ErrorEnvelope
     */
    error: ErrorEnvelopeError;
}

/**
 * Check if a given object implements the ErrorEnvelope interface.
 */
export function instanceOfErrorEnvelope(value: object): value is ErrorEnvelope {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ErrorEnvelopeFromJSON(json: any): ErrorEnvelope {
    return ErrorEnvelopeFromJSONTyped(json, false);
}

export function ErrorEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'error': ErrorEnvelopeErrorFromJSON(json['error']),
    };
}

export function ErrorEnvelopeToJSON(json: any): ErrorEnvelope {
    return ErrorEnvelopeToJSONTyped(json, false);
}

export function ErrorEnvelopeToJSONTyped(value?: ErrorEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': ErrorEnvelopeErrorToJSON(value['error']),
    };
}

