/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
    VenueToJSONTyped,
} from './Venue';
import type { EventStatus } from './EventStatus';
import {
    EventStatusFromJSON,
    EventStatusFromJSONTyped,
    EventStatusToJSON,
    EventStatusToJSONTyped,
} from './EventStatus';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';
import type { Visibility } from './Visibility';
import {
    VisibilityFromJSON,
    VisibilityFromJSONTyped,
    VisibilityToJSON,
    VisibilityToJSONTyped,
} from './Visibility';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    ownerId: string;
    /**
     * 
     * @type {EventStatus}
     * @memberof Event
     */
    status: EventStatus;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    eventType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    title?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    startsAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    timezone?: string;
    /**
     * 
     * @type {Venue}
     * @memberof Event
     */
    venue?: Venue | null;
    /**
     * 
     * @type {Visibility}
     * @memberof Event
     */
    visibility?: Visibility | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    dressCodeNotes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    canonicalUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Event
     */
    shareEligible: boolean;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    shareBlockedReason?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    publishedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    lastSavedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    updatedAt: Date;
    /**
     * 
     * @type {Array<Media>}
     * @memberof Event
     */
    media: Array<Media>;
}



/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('shareEligible' in value) || value['shareEligible'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ownerId': json['ownerId'],
        'status': EventStatusFromJSON(json['status']),
        'version': json['version'],
        'eventType': json['eventType'] == null ? undefined : json['eventType'],
        'title': json['title'] == null ? undefined : json['title'],
        'startsAt': json['startsAt'] == null ? undefined : (new Date(json['startsAt'])),
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'venue': json['venue'] == null ? undefined : VenueFromJSON(json['venue']),
        'visibility': json['visibility'] == null ? undefined : VisibilityFromJSON(json['visibility']),
        'dressCodeNotes': json['dressCodeNotes'] == null ? undefined : json['dressCodeNotes'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'canonicalUrl': json['canonicalUrl'] == null ? undefined : json['canonicalUrl'],
        'shareEligible': json['shareEligible'],
        'shareBlockedReason': json['shareBlockedReason'] == null ? undefined : json['shareBlockedReason'],
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'lastSavedAt': json['lastSavedAt'] == null ? undefined : (new Date(json['lastSavedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'media': ((json['media'] as Array<any>).map(MediaFromJSON)),
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ownerId': value['ownerId'],
        'status': EventStatusToJSON(value['status']),
        'version': value['version'],
        'eventType': value['eventType'],
        'title': value['title'],
        'startsAt': value['startsAt'] == null ? value['startsAt'] : value['startsAt'].toISOString(),
        'timezone': value['timezone'],
        'venue': VenueToJSON(value['venue']),
        'visibility': VisibilityToJSON(value['visibility']),
        'dressCodeNotes': value['dressCodeNotes'],
        'slug': value['slug'],
        'canonicalUrl': value['canonicalUrl'],
        'shareEligible': value['shareEligible'],
        'shareBlockedReason': value['shareBlockedReason'],
        'publishedAt': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'lastSavedAt': value['lastSavedAt'] == null ? value['lastSavedAt'] : value['lastSavedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'media': ((value['media'] as Array<any>).map(MediaToJSON)),
    };
}

