/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface EventWithSession
 */
export interface EventWithSession {
    /**
     * 
     * @type {Event}
     * @memberof EventWithSession
     */
    event: Event;
    /**
     * 
     * @type {string}
     * @memberof EventWithSession
     */
    creationSessionId: string;
}

/**
 * Check if a given object implements the EventWithSession interface.
 */
export function instanceOfEventWithSession(value: object): value is EventWithSession {
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('creationSessionId' in value) || value['creationSessionId'] === undefined) return false;
    return true;
}

export function EventWithSessionFromJSON(json: any): EventWithSession {
    return EventWithSessionFromJSONTyped(json, false);
}

export function EventWithSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventWithSession {
    if (json == null) {
        return json;
    }
    return {
        
        'event': EventFromJSON(json['event']),
        'creationSessionId': json['creationSessionId'],
    };
}

export function EventWithSessionToJSON(json: any): EventWithSession {
    return EventWithSessionToJSONTyped(json, false);
}

export function EventWithSessionToJSONTyped(value?: EventWithSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': EventToJSON(value['event']),
        'creationSessionId': value['creationSessionId'],
    };
}

