/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalJobResult
 */
export interface InternalJobResult {
    /**
     * 
     * @type {InternalJobResultJobEnum}
     * @memberof InternalJobResult
     */
    job: InternalJobResultJobEnum;
    /**
     * 
     * @type {Date}
     * @memberof InternalJobResult
     */
    acceptedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof InternalJobResult
     */
    examined: number;
    /**
     * 
     * @type {number}
     * @memberof InternalJobResult
     */
    affected: number;
}


/**
 * @export
 */
export const InternalJobResultJobEnum = {
    ScanDispatch: 'scan_dispatch',
    Retention: 'retention'
} as const;
export type InternalJobResultJobEnum = typeof InternalJobResultJobEnum[keyof typeof InternalJobResultJobEnum];


/**
 * Check if a given object implements the InternalJobResult interface.
 */
export function instanceOfInternalJobResult(value: object): value is InternalJobResult {
    if (!('job' in value) || value['job'] === undefined) return false;
    if (!('acceptedAt' in value) || value['acceptedAt'] === undefined) return false;
    if (!('examined' in value) || value['examined'] === undefined) return false;
    if (!('affected' in value) || value['affected'] === undefined) return false;
    return true;
}

export function InternalJobResultFromJSON(json: any): InternalJobResult {
    return InternalJobResultFromJSONTyped(json, false);
}

export function InternalJobResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalJobResult {
    if (json == null) {
        return json;
    }
    return {
        
        'job': json['job'],
        'acceptedAt': (new Date(json['acceptedAt'])),
        'examined': json['examined'],
        'affected': json['affected'],
    };
}

export function InternalJobResultToJSON(json: any): InternalJobResult {
    return InternalJobResultToJSONTyped(json, false);
}

export function InternalJobResultToJSONTyped(value?: InternalJobResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job': value['job'],
        'acceptedAt': value['acceptedAt'].toISOString(),
        'examined': value['examined'],
        'affected': value['affected'],
    };
}

