/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkIdentityRequest
 */
export interface LinkIdentityRequest {
    /**
     * Provider identity that Supabase has already linked to the authenticated user
     * @type {LinkIdentityRequestProviderEnum}
     * @memberof LinkIdentityRequest
     */
    provider: LinkIdentityRequestProviderEnum;
}


/**
 * @export
 */
export const LinkIdentityRequestProviderEnum = {
    Google: 'google',
    Email: 'email'
} as const;
export type LinkIdentityRequestProviderEnum = typeof LinkIdentityRequestProviderEnum[keyof typeof LinkIdentityRequestProviderEnum];


/**
 * Check if a given object implements the LinkIdentityRequest interface.
 */
export function instanceOfLinkIdentityRequest(value: object): value is LinkIdentityRequest {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function LinkIdentityRequestFromJSON(json: any): LinkIdentityRequest {
    return LinkIdentityRequestFromJSONTyped(json, false);
}

export function LinkIdentityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkIdentityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
    };
}

export function LinkIdentityRequestToJSON(json: any): LinkIdentityRequest {
    return LinkIdentityRequestToJSONTyped(json, false);
}

export function LinkIdentityRequestToJSONTyped(value?: LinkIdentityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
    };
}

