/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';

/**
 * 
 * @export
 * @interface ListMedia200Response
 */
export interface ListMedia200Response {
    /**
     * 
     * @type {Array<Media>}
     * @memberof ListMedia200Response
     */
    items: Array<Media>;
}

/**
 * Check if a given object implements the ListMedia200Response interface.
 */
export function instanceOfListMedia200Response(value: object): value is ListMedia200Response {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListMedia200ResponseFromJSON(json: any): ListMedia200Response {
    return ListMedia200ResponseFromJSONTyped(json, false);
}

export function ListMedia200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMedia200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MediaFromJSON)),
    };
}

export function ListMedia200ResponseToJSON(json: any): ListMedia200Response {
    return ListMedia200ResponseToJSONTyped(json, false);
}

export function ListMedia200ResponseToJSONTyped(value?: ListMedia200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MediaToJSON)),
    };
}

