/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface ListEvents200Response
 */
export interface ListEvents200Response {
    /**
     * 
     * @type {Array<Event>}
     * @memberof ListEvents200Response
     */
    items: Array<Event>;
    /**
     * 
     * @type {string}
     * @memberof ListEvents200Response
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the ListEvents200Response interface.
 */
export function instanceOfListEvents200Response(value: object): value is ListEvents200Response {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ListEvents200ResponseFromJSON(json: any): ListEvents200Response {
    return ListEvents200ResponseFromJSONTyped(json, false);
}

export function ListEvents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEvents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(EventFromJSON)),
        'nextCursor': json['nextCursor'] == null ? undefined : json['nextCursor'],
    };
}

export function ListEvents200ResponseToJSON(json: any): ListEvents200Response {
    return ListEvents200ResponseToJSONTyped(json, false);
}

export function ListEvents200ResponseToJSONTyped(value?: ListEvents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(EventToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

