/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MediaRole = {
    Invitation: 'invitation',
    AsoEbi: 'aso_ebi'
} as const;
export type MediaRole = typeof MediaRole[keyof typeof MediaRole];


export function instanceOfMediaRole(value: any): boolean {
    for (const key in MediaRole) {
        if (Object.prototype.hasOwnProperty.call(MediaRole, key)) {
            if (MediaRole[key as keyof typeof MediaRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MediaRoleFromJSON(json: any): MediaRole {
    return MediaRoleFromJSONTyped(json, false);
}

export function MediaRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaRole {
    return json as MediaRole;
}

export function MediaRoleToJSON(value?: MediaRole | null): any {
    return value as any;
}

export function MediaRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): MediaRole {
    return value as MediaRole;
}

