/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaRole } from './MediaRole';
import {
    MediaRoleFromJSON,
    MediaRoleFromJSONTyped,
    MediaRoleToJSON,
    MediaRoleToJSONTyped,
} from './MediaRole';
import type { MediaStatus } from './MediaStatus';
import {
    MediaStatusFromJSON,
    MediaStatusFromJSONTyped,
    MediaStatusToJSON,
    MediaStatusToJSONTyped,
} from './MediaStatus';

/**
 * 
 * @export
 * @interface Media
 */
export interface Media {
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    eventId: string;
    /**
     * 
     * @type {MediaRole}
     * @memberof Media
     */
    role: MediaRole;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    claimedMimeType: string;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    detectedMimeType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Media
     */
    sizeBytes: number;
    /**
     * 
     * @type {MediaStatus}
     * @memberof Media
     */
    status: MediaStatus;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    rejectionCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Media
     */
    previewUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Media
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Media
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the Media interface.
 */
export function instanceOfMedia(value: object): value is Media {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('claimedMimeType' in value) || value['claimedMimeType'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function MediaFromJSON(json: any): Media {
    return MediaFromJSONTyped(json, false);
}

export function MediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Media {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'eventId': json['eventId'],
        'role': MediaRoleFromJSON(json['role']),
        'filename': json['filename'],
        'claimedMimeType': json['claimedMimeType'],
        'detectedMimeType': json['detectedMimeType'] == null ? undefined : json['detectedMimeType'],
        'sizeBytes': json['sizeBytes'],
        'status': MediaStatusFromJSON(json['status']),
        'rejectionCode': json['rejectionCode'] == null ? undefined : json['rejectionCode'],
        'previewUrl': json['previewUrl'] == null ? undefined : json['previewUrl'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function MediaToJSON(json: any): Media {
    return MediaToJSONTyped(json, false);
}

export function MediaToJSONTyped(value?: Media | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventId': value['eventId'],
        'role': MediaRoleToJSON(value['role']),
        'filename': value['filename'],
        'claimedMimeType': value['claimedMimeType'],
        'detectedMimeType': value['detectedMimeType'],
        'sizeBytes': value['sizeBytes'],
        'status': MediaStatusToJSON(value['status']),
        'rejectionCode': value['rejectionCode'],
        'previewUrl': value['previewUrl'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

