/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MediaStatus = {
    Quarantine: 'quarantine',
    Scanning: 'scanning',
    Active: 'active',
    Rejected: 'rejected',
    Deleted: 'deleted'
} as const;
export type MediaStatus = typeof MediaStatus[keyof typeof MediaStatus];


export function instanceOfMediaStatus(value: any): boolean {
    for (const key in MediaStatus) {
        if (Object.prototype.hasOwnProperty.call(MediaStatus, key)) {
            if (MediaStatus[key as keyof typeof MediaStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MediaStatusFromJSON(json: any): MediaStatus {
    return MediaStatusFromJSONTyped(json, false);
}

export function MediaStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaStatus {
    return json as MediaStatus;
}

export function MediaStatusToJSON(value?: MediaStatus | null): any {
    return value as any;
}

export function MediaStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): MediaStatus {
    return value as MediaStatus;
}

