/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicEventMetadata
 */
export interface PublicEventMetadata {
    /**
     * 
     * @type {string}
     * @memberof PublicEventMetadata
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof PublicEventMetadata
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicEventMetadata
     */
    startsAt: Date;
    /**
     * 
     * @type {PublicEventMetadataVisibilityEnum}
     * @memberof PublicEventMetadata
     */
    visibility: PublicEventMetadataVisibilityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PublicEventMetadata
     */
    indexable: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicEventMetadata
     */
    canonicalUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PublicEventMetadata
     */
    invitationPreviewUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicEventMetadata
     */
    venueName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicEventMetadata
     */
    venueAddress?: string | null;
}


/**
 * @export
 */
export const PublicEventMetadataVisibilityEnum = {
    Public: 'public',
    PrivateLink: 'private_link'
} as const;
export type PublicEventMetadataVisibilityEnum = typeof PublicEventMetadataVisibilityEnum[keyof typeof PublicEventMetadataVisibilityEnum];


/**
 * Check if a given object implements the PublicEventMetadata interface.
 */
export function instanceOfPublicEventMetadata(value: object): value is PublicEventMetadata {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('startsAt' in value) || value['startsAt'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('indexable' in value) || value['indexable'] === undefined) return false;
    if (!('canonicalUrl' in value) || value['canonicalUrl'] === undefined) return false;
    return true;
}

export function PublicEventMetadataFromJSON(json: any): PublicEventMetadata {
    return PublicEventMetadataFromJSONTyped(json, false);
}

export function PublicEventMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicEventMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'title': json['title'],
        'startsAt': (new Date(json['startsAt'])),
        'visibility': json['visibility'],
        'indexable': json['indexable'],
        'canonicalUrl': json['canonicalUrl'],
        'invitationPreviewUrl': json['invitationPreviewUrl'] == null ? undefined : json['invitationPreviewUrl'],
        'venueName': json['venueName'] == null ? undefined : json['venueName'],
        'venueAddress': json['venueAddress'] == null ? undefined : json['venueAddress'],
    };
}

export function PublicEventMetadataToJSON(json: any): PublicEventMetadata {
    return PublicEventMetadataToJSONTyped(json, false);
}

export function PublicEventMetadataToJSONTyped(value?: PublicEventMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'title': value['title'],
        'startsAt': value['startsAt'].toISOString(),
        'visibility': value['visibility'],
        'indexable': value['indexable'],
        'canonicalUrl': value['canonicalUrl'],
        'invitationPreviewUrl': value['invitationPreviewUrl'],
        'venueName': value['venueName'],
        'venueAddress': value['venueAddress'],
    };
}

