/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface PublishEvent200Response
 */
export interface PublishEvent200Response {
    /**
     * 
     * @type {Event}
     * @memberof PublishEvent200Response
     */
    event: Event;
    /**
     * 
     * @type {string}
     * @memberof PublishEvent200Response
     */
    canonicalUrl: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublishEvent200Response
     */
    shareEligible: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublishEvent200Response
     */
    shareBlockedReason?: string | null;
}

/**
 * Check if a given object implements the PublishEvent200Response interface.
 */
export function instanceOfPublishEvent200Response(value: object): value is PublishEvent200Response {
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('canonicalUrl' in value) || value['canonicalUrl'] === undefined) return false;
    if (!('shareEligible' in value) || value['shareEligible'] === undefined) return false;
    return true;
}

export function PublishEvent200ResponseFromJSON(json: any): PublishEvent200Response {
    return PublishEvent200ResponseFromJSONTyped(json, false);
}

export function PublishEvent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishEvent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'event': EventFromJSON(json['event']),
        'canonicalUrl': json['canonicalUrl'],
        'shareEligible': json['shareEligible'],
        'shareBlockedReason': json['shareBlockedReason'] == null ? undefined : json['shareBlockedReason'],
    };
}

export function PublishEvent200ResponseToJSON(json: any): PublishEvent200Response {
    return PublishEvent200ResponseToJSONTyped(json, false);
}

export function PublishEvent200ResponseToJSONTyped(value?: PublishEvent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': EventToJSON(value['event']),
        'canonicalUrl': value['canonicalUrl'],
        'shareEligible': value['shareEligible'],
        'shareBlockedReason': value['shareBlockedReason'],
    };
}

