/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScannerCallbackRequest
 */
export interface ScannerCallbackRequest {
    /**
     * 
     * @type {string}
     * @memberof ScannerCallbackRequest
     */
    mediaId: string;
    /**
     * 
     * @type {ScannerCallbackRequestResultEnum}
     * @memberof ScannerCallbackRequest
     */
    result: ScannerCallbackRequestResultEnum;
    /**
     * 
     * @type {ScannerCallbackRequestDetectedMimeTypeEnum}
     * @memberof ScannerCallbackRequest
     */
    detectedMimeType: ScannerCallbackRequestDetectedMimeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ScannerCallbackRequest
     */
    objectSha256: string;
    /**
     * 
     * @type {ScannerCallbackRequestRejectionCodeEnum}
     * @memberof ScannerCallbackRequest
     */
    rejectionCode?: ScannerCallbackRequestRejectionCodeEnum | null;
    /**
     * 
     * @type {string}
     * @memberof ScannerCallbackRequest
     */
    previewQuarantinePath?: string;
    /**
     * 
     * @type {string}
     * @memberof ScannerCallbackRequest
     */
    previewSha256?: string;
}


/**
 * @export
 */
export const ScannerCallbackRequestResultEnum = {
    Clean: 'clean',
    Rejected: 'rejected'
} as const;
export type ScannerCallbackRequestResultEnum = typeof ScannerCallbackRequestResultEnum[keyof typeof ScannerCallbackRequestResultEnum];

/**
 * @export
 */
export const ScannerCallbackRequestDetectedMimeTypeEnum = {
    ImageJpeg: 'image/jpeg',
    ImagePng: 'image/png',
    ImageWebp: 'image/webp',
    ApplicationPdf: 'application/pdf',
    ApplicationOctetStream: 'application/octet-stream'
} as const;
export type ScannerCallbackRequestDetectedMimeTypeEnum = typeof ScannerCallbackRequestDetectedMimeTypeEnum[keyof typeof ScannerCallbackRequestDetectedMimeTypeEnum];

/**
 * @export
 */
export const ScannerCallbackRequestRejectionCodeEnum = {
    MalwareDetected: 'malware_detected',
    TypeMismatch: 'type_mismatch',
    UnsupportedType: 'unsupported_type',
    CorruptFile: 'corrupt_file',
    ScanFailed: 'scan_failed'
} as const;
export type ScannerCallbackRequestRejectionCodeEnum = typeof ScannerCallbackRequestRejectionCodeEnum[keyof typeof ScannerCallbackRequestRejectionCodeEnum];


/**
 * Check if a given object implements the ScannerCallbackRequest interface.
 */
export function instanceOfScannerCallbackRequest(value: object): value is ScannerCallbackRequest {
    if (!('mediaId' in value) || value['mediaId'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('detectedMimeType' in value) || value['detectedMimeType'] === undefined) return false;
    if (!('objectSha256' in value) || value['objectSha256'] === undefined) return false;
    return true;
}

export function ScannerCallbackRequestFromJSON(json: any): ScannerCallbackRequest {
    return ScannerCallbackRequestFromJSONTyped(json, false);
}

export function ScannerCallbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScannerCallbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaId': json['mediaId'],
        'result': json['result'],
        'detectedMimeType': json['detectedMimeType'],
        'objectSha256': json['objectSha256'],
        'rejectionCode': json['rejectionCode'] == null ? undefined : json['rejectionCode'],
        'previewQuarantinePath': json['previewQuarantinePath'] == null ? undefined : json['previewQuarantinePath'],
        'previewSha256': json['previewSha256'] == null ? undefined : json['previewSha256'],
    };
}

export function ScannerCallbackRequestToJSON(json: any): ScannerCallbackRequest {
    return ScannerCallbackRequestToJSONTyped(json, false);
}

export function ScannerCallbackRequestToJSONTyped(value?: ScannerCallbackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaId': value['mediaId'],
        'result': value['result'],
        'detectedMimeType': value['detectedMimeType'],
        'objectSha256': value['objectSha256'],
        'rejectionCode': value['rejectionCode'],
        'previewQuarantinePath': value['previewQuarantinePath'],
        'previewSha256': value['previewSha256'],
    };
}

