/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
    VenueToJSONTyped,
} from './Venue';
import type { Visibility } from './Visibility';
import {
    VisibilityFromJSON,
    VisibilityFromJSONTyped,
    VisibilityToJSON,
    VisibilityToJSONTyped,
} from './Visibility';

/**
 * 
 * @export
 * @interface UpdateEventRequest
 */
export interface UpdateEventRequest {
    /**
     * 
     * @type {UpdateEventRequestEventTypeEnum}
     * @memberof UpdateEventRequest
     */
    eventType?: UpdateEventRequestEventTypeEnum | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    title?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateEventRequest
     */
    startsAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    timezone?: string;
    /**
     * 
     * @type {Venue}
     * @memberof UpdateEventRequest
     */
    venue?: Venue | null;
    /**
     * 
     * @type {Visibility}
     * @memberof UpdateEventRequest
     */
    visibility?: Visibility | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    dressCodeNotes?: string | null;
}


/**
 * @export
 */
export const UpdateEventRequestEventTypeEnum = {
    Wedding: 'wedding',
    Birthday: 'birthday',
    NamingCeremony: 'naming_ceremony',
    Anniversary: 'anniversary',
    Graduation: 'graduation',
    Housewarming: 'housewarming',
    Other: 'other'
} as const;
export type UpdateEventRequestEventTypeEnum = typeof UpdateEventRequestEventTypeEnum[keyof typeof UpdateEventRequestEventTypeEnum];


/**
 * Check if a given object implements the UpdateEventRequest interface.
 */
export function instanceOfUpdateEventRequest(value: object): value is UpdateEventRequest {
    return true;
}

export function UpdateEventRequestFromJSON(json: any): UpdateEventRequest {
    return UpdateEventRequestFromJSONTyped(json, false);
}

export function UpdateEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'eventType': json['eventType'] == null ? undefined : json['eventType'],
        'title': json['title'] == null ? undefined : json['title'],
        'startsAt': json['startsAt'] == null ? undefined : (new Date(json['startsAt'])),
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'venue': json['venue'] == null ? undefined : VenueFromJSON(json['venue']),
        'visibility': json['visibility'] == null ? undefined : VisibilityFromJSON(json['visibility']),
        'dressCodeNotes': json['dressCodeNotes'] == null ? undefined : json['dressCodeNotes'],
    };
}

export function UpdateEventRequestToJSON(json: any): UpdateEventRequest {
    return UpdateEventRequestToJSONTyped(json, false);
}

export function UpdateEventRequestToJSONTyped(value?: UpdateEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventType': value['eventType'],
        'title': value['title'],
        'startsAt': value['startsAt'] == null ? value['startsAt'] : value['startsAt'].toISOString(),
        'timezone': value['timezone'],
        'venue': VenueToJSON(value['venue']),
        'visibility': VisibilityToJSON(value['visibility']),
        'dressCodeNotes': value['dressCodeNotes'],
    };
}

