/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Venue
 */
export interface Venue {
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    displayAddress: string;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    placeId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Venue
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Venue
     */
    longitude?: number | null;
    /**
     * Publication requires true and non-null valid coordinates
     * @type {boolean}
     * @memberof Venue
     */
    confirmed: boolean;
}

/**
 * Check if a given object implements the Venue interface.
 */
export function instanceOfVenue(value: object): value is Venue {
    if (!('displayAddress' in value) || value['displayAddress'] === undefined) return false;
    if (!('confirmed' in value) || value['confirmed'] === undefined) return false;
    return true;
}

export function VenueFromJSON(json: any): Venue {
    return VenueFromJSONTyped(json, false);
}

export function VenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): Venue {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'displayAddress': json['displayAddress'],
        'placeId': json['placeId'] == null ? undefined : json['placeId'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'confirmed': json['confirmed'],
    };
}

export function VenueToJSON(json: any): Venue {
    return VenueToJSONTyped(json, false);
}

export function VenueToJSONTyped(value?: Venue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'displayAddress': value['displayAddress'],
        'placeId': value['placeId'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'confirmed': value['confirmed'],
    };
}

