/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Visibility = {
    Public: 'public',
    PrivateLink: 'private_link',
    InviteOnly: 'invite_only',
    HiddenLocation: 'hidden_location'
} as const;
export type Visibility = typeof Visibility[keyof typeof Visibility];


export function instanceOfVisibility(value: any): boolean {
    for (const key in Visibility) {
        if (Object.prototype.hasOwnProperty.call(Visibility, key)) {
            if (Visibility[key as keyof typeof Visibility] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VisibilityFromJSON(json: any): Visibility {
    return VisibilityFromJSONTyped(json, false);
}

export function VisibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Visibility {
    return json as Visibility;
}

export function VisibilityToJSON(value?: Visibility | null): any {
    return value as any;
}

export function VisibilityToJSONTyped(value: any, ignoreDiscriminator: boolean): Visibility {
    return value as Visibility;
}

