/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WambeProductEventV1Properties
 */
export interface WambeProductEventV1Properties {
    /**
     * 
     * @type {WambeProductEventV1PropertiesStepEnum}
     * @memberof WambeProductEventV1Properties
     */
    step?: WambeProductEventV1PropertiesStepEnum;
    /**
     * 
     * @type {string}
     * @memberof WambeProductEventV1Properties
     */
    outcomeCode?: string;
    /**
     * 
     * @type {WambeProductEventV1PropertiesMediaRoleEnum}
     * @memberof WambeProductEventV1Properties
     */
    mediaRole?: WambeProductEventV1PropertiesMediaRoleEnum;
    /**
     * 
     * @type {WambeProductEventV1PropertiesVisibilityEnum}
     * @memberof WambeProductEventV1Properties
     */
    visibility?: WambeProductEventV1PropertiesVisibilityEnum;
    /**
     * 
     * @type {boolean}
     * @memberof WambeProductEventV1Properties
     */
    hadMediaUpload?: boolean;
    /**
     * 
     * @type {WambeProductEventV1PropertiesLifecycleActionEnum}
     * @memberof WambeProductEventV1Properties
     */
    lifecycleAction?: WambeProductEventV1PropertiesLifecycleActionEnum;
}


/**
 * @export
 */
export const WambeProductEventV1PropertiesStepEnum = {
    Auth: 'auth',
    Basics: 'basics',
    Venue: 'venue',
    Style: 'style',
    Privacy: 'privacy',
    Publish: 'publish',
    Share: 'share',
    Management: 'management'
} as const;
export type WambeProductEventV1PropertiesStepEnum = typeof WambeProductEventV1PropertiesStepEnum[keyof typeof WambeProductEventV1PropertiesStepEnum];

/**
 * @export
 */
export const WambeProductEventV1PropertiesMediaRoleEnum = {
    Invitation: 'invitation',
    AsoEbi: 'aso_ebi'
} as const;
export type WambeProductEventV1PropertiesMediaRoleEnum = typeof WambeProductEventV1PropertiesMediaRoleEnum[keyof typeof WambeProductEventV1PropertiesMediaRoleEnum];

/**
 * @export
 */
export const WambeProductEventV1PropertiesVisibilityEnum = {
    Public: 'public',
    PrivateLink: 'private_link',
    InviteOnly: 'invite_only',
    HiddenLocation: 'hidden_location'
} as const;
export type WambeProductEventV1PropertiesVisibilityEnum = typeof WambeProductEventV1PropertiesVisibilityEnum[keyof typeof WambeProductEventV1PropertiesVisibilityEnum];

/**
 * @export
 */
export const WambeProductEventV1PropertiesLifecycleActionEnum = {
    Published: 'published',
    Unpublished: 'unpublished',
    Republished: 'republished',
    Deleted: 'deleted'
} as const;
export type WambeProductEventV1PropertiesLifecycleActionEnum = typeof WambeProductEventV1PropertiesLifecycleActionEnum[keyof typeof WambeProductEventV1PropertiesLifecycleActionEnum];


/**
 * Check if a given object implements the WambeProductEventV1Properties interface.
 */
export function instanceOfWambeProductEventV1Properties(value: object): value is WambeProductEventV1Properties {
    return true;
}

export function WambeProductEventV1PropertiesFromJSON(json: any): WambeProductEventV1Properties {
    return WambeProductEventV1PropertiesFromJSONTyped(json, false);
}

export function WambeProductEventV1PropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): WambeProductEventV1Properties {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'] == null ? undefined : json['step'],
        'outcomeCode': json['outcomeCode'] == null ? undefined : json['outcomeCode'],
        'mediaRole': json['mediaRole'] == null ? undefined : json['mediaRole'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'hadMediaUpload': json['hadMediaUpload'] == null ? undefined : json['hadMediaUpload'],
        'lifecycleAction': json['lifecycleAction'] == null ? undefined : json['lifecycleAction'],
    };
}

export function WambeProductEventV1PropertiesToJSON(json: any): WambeProductEventV1Properties {
    return WambeProductEventV1PropertiesToJSONTyped(json, false);
}

export function WambeProductEventV1PropertiesToJSONTyped(value?: WambeProductEventV1Properties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step': value['step'],
        'outcomeCode': value['outcomeCode'],
        'mediaRole': value['mediaRole'],
        'visibility': value['visibility'],
        'hadMediaUpload': value['hadMediaUpload'],
        'lifecycleAction': value['lifecycleAction'],
    };
}

