/* tslint:disable */
/* eslint-disable */
/**
 * Wambe Host Event API
 * Architecture-owned contract for US-002 host authentication integration, event lifecycle, media, and creation milestones.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WambeProductEventV1Properties } from './WambeProductEventV1Properties';
import {
    WambeProductEventV1PropertiesFromJSON,
    WambeProductEventV1PropertiesFromJSONTyped,
    WambeProductEventV1PropertiesToJSON,
    WambeProductEventV1PropertiesToJSONTyped,
} from './WambeProductEventV1Properties';

/**
 * 
 * @export
 * @interface WambeProductEventV1
 */
export interface WambeProductEventV1 {
    /**
     * 
     * @type {any}
     * @memberof WambeProductEventV1
     */
    schemaVersion: any | null;
    /**
     * 
     * @type {WambeProductEventV1NameEnum}
     * @memberof WambeProductEventV1
     */
    name: WambeProductEventV1NameEnum;
    /**
     * 
     * @type {string}
     * @memberof WambeProductEventV1
     */
    eventId: string;
    /**
     * 
     * @type {string}
     * @memberof WambeProductEventV1
     */
    creationSessionId: string;
    /**
     * 
     * @type {Date}
     * @memberof WambeProductEventV1
     */
    occurredAt: Date;
    /**
     * 
     * @type {WambeProductEventV1EligibilityEnum}
     * @memberof WambeProductEventV1
     */
    eligibility: WambeProductEventV1EligibilityEnum;
    /**
     * 
     * @type {WambeProductEventV1DeviceClassEnum}
     * @memberof WambeProductEventV1
     */
    deviceClass: WambeProductEventV1DeviceClassEnum;
    /**
     * 
     * @type {WambeProductEventV1NetworkQualityEnum}
     * @memberof WambeProductEventV1
     */
    networkQuality: WambeProductEventV1NetworkQualityEnum;
    /**
     * 
     * @type {WambeProductEventV1Properties}
     * @memberof WambeProductEventV1
     */
    properties: WambeProductEventV1Properties;
}


/**
 * @export
 */
export const WambeProductEventV1NameEnum = {
    EventCreationStarted: 'event_creation_started',
    DraftSaveSucceeded: 'draft_save_succeeded',
    DraftSaveFailed: 'draft_save_failed',
    ValidationFailed: 'validation_failed',
    MediaUploadSucceeded: 'media_upload_succeeded',
    MediaUploadFailed: 'media_upload_failed',
    EventPublishSucceeded: 'event_publish_succeeded',
    EventPublishFailed: 'event_publish_failed',
    ShareClicked: 'share_clicked',
    EventLifecycleChanged: 'event_lifecycle_changed'
} as const;
export type WambeProductEventV1NameEnum = typeof WambeProductEventV1NameEnum[keyof typeof WambeProductEventV1NameEnum];

/**
 * @export
 */
export const WambeProductEventV1EligibilityEnum = {
    EligibleFirstTime: 'eligible_first_time',
    ResumedDraft: 'resumed_draft',
    StaffAssisted: 'staff_assisted'
} as const;
export type WambeProductEventV1EligibilityEnum = typeof WambeProductEventV1EligibilityEnum[keyof typeof WambeProductEventV1EligibilityEnum];

/**
 * @export
 */
export const WambeProductEventV1DeviceClassEnum = {
    Mobile: 'mobile',
    Tablet: 'tablet',
    Desktop: 'desktop',
    Unknown: 'unknown'
} as const;
export type WambeProductEventV1DeviceClassEnum = typeof WambeProductEventV1DeviceClassEnum[keyof typeof WambeProductEventV1DeviceClassEnum];

/**
 * @export
 */
export const WambeProductEventV1NetworkQualityEnum = {
    Good: 'good',
    Fair: 'fair',
    Poor: 'poor',
    Unknown: 'unknown'
} as const;
export type WambeProductEventV1NetworkQualityEnum = typeof WambeProductEventV1NetworkQualityEnum[keyof typeof WambeProductEventV1NetworkQualityEnum];


/**
 * Check if a given object implements the WambeProductEventV1 interface.
 */
export function instanceOfWambeProductEventV1(value: object): value is WambeProductEventV1 {
    if (!('schemaVersion' in value) || value['schemaVersion'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('creationSessionId' in value) || value['creationSessionId'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    if (!('eligibility' in value) || value['eligibility'] === undefined) return false;
    if (!('deviceClass' in value) || value['deviceClass'] === undefined) return false;
    if (!('networkQuality' in value) || value['networkQuality'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function WambeProductEventV1FromJSON(json: any): WambeProductEventV1 {
    return WambeProductEventV1FromJSONTyped(json, false);
}

export function WambeProductEventV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): WambeProductEventV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'schemaVersion': json['schemaVersion'],
        'name': json['name'],
        'eventId': json['eventId'],
        'creationSessionId': json['creationSessionId'],
        'occurredAt': (new Date(json['occurredAt'])),
        'eligibility': json['eligibility'],
        'deviceClass': json['deviceClass'],
        'networkQuality': json['networkQuality'],
        'properties': WambeProductEventV1PropertiesFromJSON(json['properties']),
    };
}

export function WambeProductEventV1ToJSON(json: any): WambeProductEventV1 {
    return WambeProductEventV1ToJSONTyped(json, false);
}

export function WambeProductEventV1ToJSONTyped(value?: WambeProductEventV1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schemaVersion': value['schemaVersion'],
        'name': value['name'],
        'eventId': value['eventId'],
        'creationSessionId': value['creationSessionId'],
        'occurredAt': value['occurredAt'].toISOString(),
        'eligibility': value['eligibility'],
        'deviceClass': value['deviceClass'],
        'networkQuality': value['networkQuality'],
        'properties': WambeProductEventV1PropertiesToJSON(value['properties']),
    };
}

